
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from webdriver_manager.chrome import ChromeDriverManager
driver= webdriver.Chrome(ChromeDriverManager().install())
driver.get("https://URL /")
driver.maximize_window()
time.sleep(3)
driver.find_element_by_link_text("Login").click()
driver.find_element_by_id("number").send_keys("+919999999999")
time.sleep(8)
driver.find_element_by_id("getOtpButton").click()
time.sleep(4)
driver.find_element_by_id("verificationCode").send_keys("999999")
time.sleep(8)
driver.find_element_by_xpath("//*[@id='verificationForm']/button").click()
time.sleep(5)
Select(driver.find_element_by_id("branch")).select_by_visible_text("TTK Mahal")
time.sleep(3)
Select(driver.find_element_by_id("room_type")).select_by_visible_text("Super Deluxe")
time.sleep(3)
driver.find_element_by_xpath("//*[@id='checkin']").send_keys("12082023")
time.sleep(3)
driver.find_element_by_id("checkout").send_keys("13082023")
time.sleep(5)
driver.find_element_by_xpath("/html/body/div[6]/div[3]/div/div/form/div/div[5]/button").click()
time.sleep(5)
driver.find_element_by_id("104").click()
time.sleep(5)
driver.find_element_by_xpath("//*[@id='cart']/div[3]/div/button[1]").click()
time.sleep(5)
driver.find_element_by_xpath("/html/body/div[3]/div/div[2]/form/button").click()
driver.find_element_by_xpath("//*[@id='rzp-button1']").click()
time.sleep(5)
driver.switch_to.frame(driver.find_element_by_class_name("razorpay-checkout-frame"))
driver.find_element_by_xpath("//*[@id='form-common']/div[1]/div[1]/div/div/div/div/button[3]").click()
time.sleep(5)
driver.find_element_by_xpath("//*[@id='bank-item-YESB']/label").click()
driver.find_element_by_id("redesign-v15-cta").click()
time.sleep(5)
driver.switch_to.window(driver.window_handles[1])
print(driver.title)

driver.find_element_by_class_name("danger").click()

driver.quit()
